before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format: zip
    replacements:
      amd64: x86_64
      darwin: macOS
    files:
      - LICENSE
      - CREDITS
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^refactor:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
